name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]

    name: 'PHP ${{ matrix.php }}'

    steps:
      - uses: actions/checkout@master

      - name: Select PHP version
        run: sudo update-alternatives --set php $(which php${{ matrix.php }})

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: composer test